"""Eye calibration service for normalized eye landmark data."""

from __future__ import annotations

from dataclasses import dataclass, field
from threading import RLock
from time import time

import numpy as np

from backend.eye_tracking.face_mesh_service import EyeData
from backend.utils.logger import get_logger

logger = get_logger(__name__)


@dataclass(frozen=True)
class CalibrationPoint:
    """Normalized screen-space calibration target."""

    index: int
    x: float
    y: float


@dataclass(frozen=True)
class EyeCenter:
    """Normalized midpoint derived from left and right eye landmarks."""

    x: float
    y: float


@dataclass(frozen=True)
class CalibrationSample:
    """Eye landmark sample captured for one calibration target."""

    point: CalibrationPoint
    eye_data: EyeData
    eye_center: EyeCenter
    captured_at: float


@dataclass(frozen=True)
class CalibrationMapping:
    """Affine mapping from normalized eye center to normalized target point."""

    x_coefficients: tuple[float, float, float]
    y_coefficients: tuple[float, float, float]
    sample_count: int


@dataclass(frozen=True)
class CalibrationProgress:
    """Current calibration progress."""

    current_point: CalibrationPoint | None
    completed_points: int
    total_points: int
    progress: float
    complete: bool


@dataclass(frozen=True)
class CalibrationState:
    """Saved calibration state for future gaze/cursor tracking modules."""

    points: tuple[CalibrationPoint, ...]
    samples: tuple[CalibrationSample, ...]
    mapping: CalibrationMapping | None
    complete: bool
    updated_at: float


@dataclass
class EyeCalibrationService:
    """Guide and store a 9-point eye calibration flow.

    The service consumes normalized ``EyeData`` generated by the existing
    FaceMeshService. It does not read camera frames, instantiate MediaPipe, or
    move the cursor.
    """

    points: tuple[CalibrationPoint, ...] = field(
        default_factory=lambda: (
            CalibrationPoint(index=0, x=0.1, y=0.1),
            CalibrationPoint(index=1, x=0.5, y=0.1),
            CalibrationPoint(index=2, x=0.9, y=0.1),
            CalibrationPoint(index=3, x=0.1, y=0.5),
            CalibrationPoint(index=4, x=0.5, y=0.5),
            CalibrationPoint(index=5, x=0.9, y=0.5),
            CalibrationPoint(index=6, x=0.1, y=0.9),
            CalibrationPoint(index=7, x=0.5, y=0.9),
            CalibrationPoint(index=8, x=0.9, y=0.9),
        )
    )

    def __post_init__(self) -> None:
        """Initialize mutable calibration state."""
        if len(self.points) != 9:
            raise ValueError("Eye calibration requires exactly 9 calibration points.")
        for point in self.points:
            if not 0.0 <= point.x <= 1.0 or not 0.0 <= point.y <= 1.0:
                raise ValueError("Calibration points must use normalized coordinates.")

        self._samples: list[CalibrationSample] = []
        self._saved_state: CalibrationState | None = None
        self._mapping: CalibrationMapping | None = None
        self._lock = RLock()

    def restart(self) -> CalibrationProgress:
        """Clear collected samples and restart calibration from the first point."""
        with self._lock:
            self._samples.clear()
            self._saved_state = None
            self._mapping = None
            logger.info("Eye calibration restarted.")
            return self.get_progress()

    def get_progress(self) -> CalibrationProgress:
        """Return the current calibration progress."""
        with self._lock:
            completed = len(self._samples)
            total = len(self.points)
            current_point = None if completed >= total else self.points[completed]

            return CalibrationProgress(
                current_point=current_point,
                completed_points=completed,
                total_points=total,
                progress=completed / total,
                complete=completed == total and self._mapping is not None,
            )

    def record_current_point(self, eye_data: EyeData) -> CalibrationProgress:
        """Store normalized eye coordinates for the current calibration point."""
        with self._lock:
            progress = self.get_progress()
            if progress.complete or progress.current_point is None:
                logger.info("Ignoring calibration sample; calibration is already complete.")
                return progress

            try:
                eye_center = self._compute_eye_center(eye_data)
            except ValueError as exc:
                logger.warning("Skipping invalid eye calibration sample: %s", exc)
                return progress

            sample = CalibrationSample(
                point=progress.current_point,
                eye_data=eye_data,
                eye_center=eye_center,
                captured_at=time(),
            )
            self._samples.append(sample)
            logger.info(
                "Captured eye calibration sample %d/%d.",
                len(self._samples),
                len(self.points),
            )

            if len(self._samples) == len(self.points):
                self._mapping = self._compute_mapping(self._samples)

            self.save_state()

            return self.get_progress()

    def get_mapping(self) -> CalibrationMapping | None:
        """Return computed calibration mapping values, if calibration is complete."""
        with self._lock:
            return self._mapping

    def save_state(self) -> CalibrationState:
        """Save and return the current calibration state."""
        with self._lock:
            self._saved_state = CalibrationState(
                points=self.points,
                samples=tuple(self._samples),
                mapping=self._mapping,
                complete=len(self._samples) == len(self.points) and self._mapping is not None,
                updated_at=time(),
            )
            logger.info("Eye calibration state saved.")
            return self._saved_state

    def get_state(self) -> CalibrationState:
        """Return the saved state, saving the current in-memory state if needed."""
        with self._lock:
            if self._saved_state is None:
                return self.save_state()
            return self._saved_state

    def _compute_eye_center(self, eye_data: EyeData) -> EyeCenter:
        """Compute one normalized eye-center point from both eyes."""
        landmarks = eye_data.left_eye + eye_data.right_eye
        if not landmarks:
            raise ValueError("Cannot calibrate without eye landmarks.")

        return EyeCenter(
            x=sum(landmark.x for landmark in landmarks) / len(landmarks),
            y=sum(landmark.y for landmark in landmarks) / len(landmarks),
        )

    def _compute_mapping(self, samples: list[CalibrationSample]) -> CalibrationMapping | None:
        """Compute affine mapping values from eye centers to calibration points."""
        if len(samples) < 3:
            raise ValueError("At least 3 samples are required to compute calibration mapping.")

        inputs = np.array(
            [[sample.eye_center.x, sample.eye_center.y, 1.0] for sample in samples],
            dtype=float,
        )
        target_x = np.array([sample.point.x for sample in samples], dtype=float)
        target_y = np.array([sample.point.y for sample in samples], dtype=float)

        if np.linalg.matrix_rank(inputs) < 3:
            logger.warning("Eye calibration samples are degenerate; mapping was not computed.")
            return None

        try:
            x_coefficients = np.linalg.lstsq(inputs, target_x, rcond=None)[0]
            y_coefficients = np.linalg.lstsq(inputs, target_y, rcond=None)[0]
        except np.linalg.LinAlgError:
            logger.exception("Eye calibration mapping computation failed.")
            return None

        logger.info("Computed eye calibration mapping from %d samples.", len(samples))
        return CalibrationMapping(
            x_coefficients=tuple(float(value) for value in x_coefficients),
            y_coefficients=tuple(float(value) for value in y_coefficients),
            sample_count=len(samples),
        )
