"""Eye calibration service for normalized eye landmark data."""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from math import hypot, isfinite, sqrt
from statistics import median
from threading import RLock
from time import time

import numpy as np

from backend.core.config.eye_config import (
    LEFT_EAR_LANDMARK_INDICES as LEFT_EAR_INDICES,
    RIGHT_EAR_LANDMARK_INDICES as RIGHT_EAR_INDICES,
)
from backend.eye_tracking.eye_interaction_config import (
    EyeInteractionConfig,
    default_eye_interaction_config,
)
from backend.eye_tracking.face_mesh_service import (
    EyeData,
    LEFT_EYE_LANDMARK_INDICES,
    NormalizedLandmark,
    RIGHT_EYE_LANDMARK_INDICES,
)
from backend.utils.helpers import compute_eye_center
from backend.utils.logger import get_logger

logger = get_logger(__name__)

_EXPECTED_EYE_LANDMARKS = len(LEFT_EYE_LANDMARK_INDICES)
_MAD_TO_STD = 1.4826


@dataclass(frozen=True)
class CalibrationPoint:
    """Normalized screen-space calibration target."""

    index: int
    x: float
    y: float


@dataclass(frozen=True)
class EyeCenter:
    """Normalized midpoint derived from left and right eye landmarks."""

    x: float
    y: float


@dataclass(frozen=True)
class CalibrationSample:
    """Eye landmark sample captured for one calibration target."""

    point: CalibrationPoint
    eye_data: EyeData
    eye_center: EyeCenter
    captured_at: float


@dataclass(frozen=True)
class CalibrationQuality:
    """Post-calibration fit quality and recalibration recommendation."""

    score: float
    rmse: float
    label: str
    recommend_recalibration: bool


@dataclass(frozen=True)
class CalibrationMapping:
    """Affine mapping from normalized eye center to normalized target point."""

    x_coefficients: tuple[float, float, float]
    y_coefficients: tuple[float, float, float]
    sample_count: int
    quality: CalibrationQuality | None = None


@dataclass(frozen=True)
class CalibrationProgress:
    """Current calibration progress."""

    current_point: CalibrationPoint | None
    completed_points: int
    total_points: int
    progress: float
    complete: bool
    quality: CalibrationQuality | None = None


@dataclass(frozen=True)
class CalibrationState:
    """Saved calibration state for future gaze/cursor tracking modules."""

    points: tuple[CalibrationPoint, ...]
    samples: tuple[CalibrationSample, ...]
    mapping: CalibrationMapping | None
    complete: bool
    updated_at: float
    quality: CalibrationQuality | None = None


class CalibrationCaptureError(ValueError):
    """Raised when a calibration point cannot be captured from stable samples."""


@dataclass
class EyeCalibrationService:
    """Guide and store a 9-point eye calibration flow.

    The service consumes normalized ``EyeData`` generated by the existing
    FaceMeshService. It does not read camera frames, instantiate MediaPipe, or
    move the cursor.
    """

    points: tuple[CalibrationPoint, ...] = field(
        default_factory=lambda: (
            CalibrationPoint(index=0, x=0.10, y=0.10),
            CalibrationPoint(index=1, x=0.50, y=0.10),
            CalibrationPoint(index=2, x=0.90, y=0.10),
            CalibrationPoint(index=3, x=0.10, y=0.50),
            CalibrationPoint(index=4, x=0.50, y=0.50),
            CalibrationPoint(index=5, x=0.90, y=0.50),
            CalibrationPoint(index=6, x=0.10, y=0.88),
            CalibrationPoint(index=7, x=0.50, y=0.88),
            CalibrationPoint(index=8, x=0.90, y=0.88),
        )
    )
    eye_config: EyeInteractionConfig | None = None

    def __post_init__(self) -> None:
        """Initialize mutable calibration state."""
        if len(self.points) != 9:
            raise ValueError("Eye calibration requires exactly 9 calibration points.")
        for point in self.points:
            if not 0.0 <= point.x <= 1.0 or not 0.0 <= point.y <= 1.0:
                raise ValueError("Calibration points must use normalized coordinates.")

        config = self.eye_config or default_eye_interaction_config()
        config.validate()
        object.__setattr__(self, "eye_config", config)

        self._samples: list[CalibrationSample] = []
        self._saved_state: CalibrationState | None = None
        self._mapping: CalibrationMapping | None = None
        self._quality: CalibrationQuality | None = None
        self._lock = RLock()

    def restart(self) -> CalibrationProgress:
        """Clear collected samples and restart calibration from the first point."""
        with self._lock:
            self._samples.clear()
            self._saved_state = None
            self._mapping = None
            self._quality = None
            logger.info("Eye calibration restarted.")
            return self.get_progress()

    def get_progress(self) -> CalibrationProgress:
        """Return the current calibration progress."""
        with self._lock:
            completed = len(self._samples)
            total = len(self.points)
            current_point = None if completed >= total else self.points[completed]

            return CalibrationProgress(
                current_point=current_point,
                completed_points=completed,
                total_points=total,
                progress=completed / total,
                complete=completed == total and self._mapping is not None,
                quality=self._quality,
            )

    def get_quality(self) -> CalibrationQuality | None:
        """Return the latest calibration quality score, if available."""
        with self._lock:
            return self._quality

    def record_current_point(self, eye_data: EyeData) -> CalibrationProgress:
        """Store one eye frame for the current point (compat path)."""
        return self.record_current_point_from_samples((eye_data,))

    def record_current_point_from_samples(
        self,
        eye_samples: Sequence[EyeData],
    ) -> CalibrationProgress:
        """Average stable gaze samples and store one calibration point."""
        with self._lock:
            progress = self.get_progress()
            if progress.complete or progress.current_point is None:
                logger.info("Ignoring calibration sample; calibration is already complete.")
                return progress

            try:
                averaged_eye_data, eye_center, accepted = self._aggregate_stable_samples(
                    eye_samples
                )
            except CalibrationCaptureError as exc:
                logger.warning("Skipping unstable eye calibration capture: %s", exc)
                raise

            sample = CalibrationSample(
                point=progress.current_point,
                eye_data=averaged_eye_data,
                eye_center=eye_center,
                captured_at=time(),
            )
            self._samples.append(sample)
            logger.info(
                "Captured eye calibration sample %d/%d from %d averaged frames.",
                len(self._samples),
                len(self.points),
                accepted,
            )

            if len(self._samples) == len(self.points):
                self._mapping = self._compute_mapping(self._samples)
                self._quality = self._mapping.quality if self._mapping is not None else None
                if self._quality is not None and self._quality.recommend_recalibration:
                    logger.warning(
                        "Calibration quality is %s (score=%.2f, rmse=%.4f). Recalibration recommended.",
                        self._quality.label,
                        self._quality.score,
                        self._quality.rmse,
                    )

            self.save_state()
            return self.get_progress()

    def get_mapping(self) -> CalibrationMapping | None:
        """Return computed calibration mapping values, if calibration is complete."""
        with self._lock:
            return self._mapping

    def save_state(self) -> CalibrationState:
        """Save and return the current calibration state."""
        with self._lock:
            self._saved_state = CalibrationState(
                points=self.points,
                samples=tuple(self._samples),
                mapping=self._mapping,
                complete=len(self._samples) == len(self.points) and self._mapping is not None,
                updated_at=time(),
                quality=self._quality,
            )
            logger.info("Eye calibration state saved.")
            return self._saved_state

    def get_state(self) -> CalibrationState:
        """Return the saved state, saving the current in-memory state if needed."""
        with self._lock:
            if self._saved_state is None:
                return self.save_state()
            return self._saved_state

    def _aggregate_stable_samples(
        self,
        eye_samples: Sequence[EyeData],
    ) -> tuple[EyeData, EyeCenter, int]:
        """Validate, reject outliers, and average consecutive gaze samples."""
        assert self.eye_config is not None
        progress = self.get_progress()
        current_pt = progress.current_point
        pt_idx = current_pt.index if current_pt else -1
        pt_x = current_pt.x if current_pt else 0.0
        pt_y = current_pt.y if current_pt else 0.0

        if not eye_samples:
            msg = "No eye landmark samples were collected from the camera stream."
            logger.warning(
                "[CALIBRATION DIAGNOSTIC] Point %d/9 Target: (%.2f, %.2f) FAILED: %s",
                pt_idx + 1, pt_x, pt_y, msg
            )
            raise CalibrationCaptureError(msg)

        valid_frames: list[EyeData] = []
        centers: list[EyeCenter] = []
        previous_center: EyeCenter | None = None
        invalid_landmark_or_blink_count = 0
        jump_rejected_count = 0

        for eye_data in eye_samples:
            if not self._is_valid_calibration_frame(eye_data):
                invalid_landmark_or_blink_count += 1
                continue

            try:
                center = self._compute_eye_center(eye_data)
            except ValueError:
                invalid_landmark_or_blink_count += 1
                continue

            if previous_center is not None:
                jump = hypot(center.x - previous_center.x, center.y - previous_center.y)
                if jump > self.eye_config.calibration_max_center_jump:
                    jump_rejected_count += 1
                    continue

            valid_frames.append(eye_data)
            centers.append(center)
            previous_center = center

        if len(valid_frames) < self.eye_config.calibration_min_valid_samples:
            exc_msg = (
                f"Only {len(valid_frames)} stable samples available (processed {len(eye_samples)} frames, "
                f"{invalid_landmark_or_blink_count} blinks/lost, {jump_rejected_count} jumps); "
                f"need at least {self.eye_config.calibration_min_valid_samples}."
            )
            logger.warning(
                "[CALIBRATION DIAGNOSTIC] Point %d/9 Target: (%.2f, %.2f) FAILED: %s",
                pt_idx + 1, pt_x, pt_y, exc_msg
            )
            raise CalibrationCaptureError(exc_msg)

        kept_indices = self._select_inlier_indices(centers)
        outlier_rejected_count = len(valid_frames) - len(kept_indices)

        if len(kept_indices) < self.eye_config.calibration_min_valid_samples:
            exc_msg = (
                f"Only {len(kept_indices)} inlier samples remained after outlier rejection "
                f"({outlier_rejected_count} outliers rejected from {len(valid_frames)} frames); "
                f"need at least {self.eye_config.calibration_min_valid_samples}."
            )
            logger.warning(
                "[CALIBRATION DIAGNOSTIC] Point %d/9 Target: (%.2f, %.2f) FAILED: %s",
                pt_idx + 1, pt_x, pt_y, exc_msg
            )
            raise CalibrationCaptureError(exc_msg)

        kept_frames = [valid_frames[index] for index in kept_indices]
        kept_centers = [centers[index] for index in kept_indices]
        mean_x = sum(center.x for center in kept_centers) / len(kept_centers)
        mean_y = sum(center.y for center in kept_centers) / len(kept_centers)
        dispersion = sqrt(
            sum((center.x - mean_x) ** 2 + (center.y - mean_y) ** 2 for center in kept_centers)
            / len(kept_centers)
        )
        if dispersion > self.eye_config.calibration_max_sample_dispersion:
            exc_msg = (
                f"Gaze dispersion {dispersion:.4f} exceeds {self.eye_config.calibration_max_sample_dispersion:.4f}; "
                "hold still and look directly at the target."
            )
            logger.warning(
                "[CALIBRATION DIAGNOSTIC] Point %d/9 Target: (%.2f, %.2f) FAILED: %s",
                pt_idx + 1, pt_x, pt_y, exc_msg
            )
            raise CalibrationCaptureError(exc_msg)

        averaged_eye_data = self._average_eye_data(kept_frames)
        eye_center = EyeCenter(x=mean_x, y=mean_y)
        logger.info(
            "[CALIBRATION DIAGNOSTIC] Point %d/9 Target: (%.2f, %.2f) CAPTURED SUCCESSFULLY "
            "(frames=%d, valid=%d, inliers=%d, dispersion=%.4f, center=(%.4f, %.4f))",
            pt_idx + 1, pt_x, pt_y, len(eye_samples), len(valid_frames), len(kept_indices), dispersion, mean_x, mean_y
        )
        return averaged_eye_data, eye_center, len(kept_centers)

    def _is_valid_calibration_frame(self, eye_data: EyeData) -> bool:
        """Reject missing landmarks, blinks, and non-finite coordinates."""
        assert self.eye_config is not None
        if (
            len(eye_data.left_eye) != _EXPECTED_EYE_LANDMARKS
            or len(eye_data.right_eye) != _EXPECTED_EYE_LANDMARKS
        ):
            return False

        for landmark in eye_data.left_eye + eye_data.right_eye:
            if not (
                isfinite(landmark.x)
                and isfinite(landmark.y)
                and isfinite(landmark.z)
                and 0.0 <= landmark.x <= 1.0
                and 0.0 <= landmark.y <= 1.0
            ):
                return False

        try:
            left_ear = self._calculate_ear(eye_data.left_eye, LEFT_EAR_INDICES)
            right_ear = self._calculate_ear(eye_data.right_eye, RIGHT_EAR_INDICES)
        except ValueError:
            return False

        # Require both eyes open (not closed in a blink) so blink frames never enter the average.
        # During downgaze (e.g. Points 7, 8, 9), eyelids naturally lower slightly (EAR ~0.22-0.25).
        # We check ear >= ear_close_threshold so closed-eye blinks (< 0.21) are rejected while
        # open downgaze eye frames are accepted.
        min_ear = self.eye_config.ear_close_threshold
        return left_ear >= min_ear and right_ear >= min_ear

    def _select_inlier_indices(self, centers: Sequence[EyeCenter]) -> list[int]:
        """Keep samples within a robust MAD envelope around the median center."""
        assert self.eye_config is not None
        if len(centers) <= 2:
            return list(range(len(centers)))

        xs = [center.x for center in centers]
        ys = [center.y for center in centers]
        median_x = median(xs)
        median_y = median(ys)
        mad_x = median([abs(value - median_x) for value in xs])
        mad_y = median([abs(value - median_y) for value in ys])

        # Fall back to a small absolute floor when MAD collapses (very stable gaze).
        scale = self.eye_config.calibration_outlier_mad_scale * _MAD_TO_STD
        limit_x = max(mad_x * scale, 1e-4)
        limit_y = max(mad_y * scale, 1e-4)

        return [
            index
            for index, center in enumerate(centers)
            if abs(center.x - median_x) <= limit_x and abs(center.y - median_y) <= limit_y
        ]

    def _average_eye_data(self, eye_samples: Sequence[EyeData]) -> EyeData:
        """Average landmark coordinates across accepted frames."""
        return EyeData(
            left_eye=self._average_landmarks(
                [sample.left_eye for sample in eye_samples]
            ),
            right_eye=self._average_landmarks(
                [sample.right_eye for sample in eye_samples]
            ),
        )

    def _average_landmarks(
        self,
        landmark_groups: Sequence[tuple[NormalizedLandmark, ...]],
    ) -> tuple[NormalizedLandmark, ...]:
        """Average corresponding landmarks across frames."""
        if not landmark_groups:
            raise CalibrationCaptureError("Cannot average an empty landmark set.")

        landmark_count = len(landmark_groups[0])
        averaged: list[NormalizedLandmark] = []
        for landmark_index in range(landmark_count):
            points = [group[landmark_index] for group in landmark_groups]
            averaged.append(
                NormalizedLandmark(
                    index=points[0].index,
                    x=sum(point.x for point in points) / len(points),
                    y=sum(point.y for point in points) / len(points),
                    z=sum(point.z for point in points) / len(points),
                )
            )
        return tuple(averaged)

    def _calculate_ear(
        self,
        landmarks: tuple[NormalizedLandmark, ...],
        indices: tuple[int, int, int, int, int, int],
    ) -> float:
        """Calculate Eye Aspect Ratio for blink rejection during capture."""
        points = {landmark.index: landmark for landmark in landmarks}
        try:
            p1, p2, p3, p4, p5, p6 = (points[index] for index in indices)
        except KeyError as exc:
            raise ValueError(f"missing EAR landmark index {exc.args[0]}") from exc

        vertical_1 = hypot(p2.x - p6.x, p2.y - p6.y)
        vertical_2 = hypot(p3.x - p5.x, p3.y - p5.y)
        horizontal = hypot(p1.x - p4.x, p1.y - p4.y)
        if horizontal <= 0.0:
            raise ValueError("horizontal eye distance is zero")

        ear = (vertical_1 + vertical_2) / (2.0 * horizontal)
        if not isfinite(ear):
            raise ValueError("EAR is not finite")
        return ear

    def _compute_eye_center(self, eye_data: EyeData) -> EyeCenter:
        """Compute one normalized eye-center point from both eyes."""
        # Sprint 1: shared helper removes duplicate eye-center averaging logic.
        center = compute_eye_center(eye_data)
        if center is None:
            raise ValueError("Cannot calibrate without eye landmarks.")

        x, y = center
        if not isfinite(x) or not isfinite(y):
            raise ValueError("eye center contains non-finite coordinates")

        return EyeCenter(x=x, y=y)

    def _compute_mapping(self, samples: list[CalibrationSample]) -> CalibrationMapping | None:
        """Compute affine mapping values from eye centers to calibration points."""
        if len(samples) < 3:
            raise ValueError("At least 3 samples are required to compute calibration mapping.")

        inputs = np.array(
            [[sample.eye_center.x, sample.eye_center.y, 1.0] for sample in samples],
            dtype=float,
        )
        target_x = np.array([sample.point.x for sample in samples], dtype=float)
        target_y = np.array([sample.point.y for sample in samples], dtype=float)

        if np.linalg.matrix_rank(inputs) < 3:
            logger.warning("Eye calibration samples are degenerate; mapping was not computed.")
            return None

        try:
            x_coefficients = np.linalg.lstsq(inputs, target_x, rcond=None)[0]
            y_coefficients = np.linalg.lstsq(inputs, target_y, rcond=None)[0]
        except np.linalg.LinAlgError:
            logger.exception("Eye calibration mapping computation failed.")
            return None

        quality = self._evaluate_quality(
            samples=samples,
            x_coefficients=tuple(float(value) for value in x_coefficients),
            y_coefficients=tuple(float(value) for value in y_coefficients),
        )
        logger.info(
            "Computed eye calibration mapping from %d samples (quality=%s score=%.2f).",
            len(samples),
            quality.label,
            quality.score,
        )
        return CalibrationMapping(
            x_coefficients=tuple(float(value) for value in x_coefficients),
            y_coefficients=tuple(float(value) for value in y_coefficients),
            sample_count=len(samples),
            quality=quality,
        )

    def _evaluate_quality(
        self,
        samples: list[CalibrationSample],
        x_coefficients: tuple[float, float, float],
        y_coefficients: tuple[float, float, float],
    ) -> CalibrationQuality:
        """Score calibration fit using in-sample 2D RMSE against target points.

        RMSE = sqrt(mean(dx^2 + dy^2)) in normalized screen coordinates [0, 1].
        Score = 1 / (1 + rmse * calibration_rmse_scale), clamped to [0, 1].

        Labels (webcam usability interpretation; score formula unchanged):
        - good: score >= calibration_good_score_threshold
        - fair: score >= calibration_quality_threshold (cursor still usable)
        - poor: below threshold (recommend recalibration)
        """
        assert self.eye_config is not None
        squared_error = 0.0
        for sample in samples:
            predicted_x = (
                x_coefficients[0] * sample.eye_center.x
                + x_coefficients[1] * sample.eye_center.y
                + x_coefficients[2]
            )
            predicted_y = (
                y_coefficients[0] * sample.eye_center.x
                + y_coefficients[1] * sample.eye_center.y
                + y_coefficients[2]
            )
            dx = predicted_x - sample.point.x
            dy = predicted_y - sample.point.y
            squared_error += dx * dx + dy * dy

        rmse = sqrt(squared_error / max(len(samples), 1))
        score = 1.0 / (1.0 + rmse * self.eye_config.calibration_rmse_scale)
        score = min(max(score, 0.0), 1.0)

        if score >= self.eye_config.calibration_good_score_threshold:
            label = "good"
        elif score >= self.eye_config.calibration_quality_threshold:
            label = "fair"
        else:
            label = "poor"

        return CalibrationQuality(
            score=score,
            rmse=rmse,
            label=label,
            recommend_recalibration=score < self.eye_config.calibration_quality_threshold,
        )
